### ISSUE TITLE
error: `The model gtp-4 does not exist`

### ISSUE THREAD

**Issue by wuqui** [debanjandhar12/logseq-chatgpt-plugin#18]
I would like to use GPT-4. I have the paid account from OpenAI and can use it on their website. However, when I select `gpt-4` in the plugin settings dropdown, I get the following error:

`The model gtp-4 does not exist`

What’s wrong here and what can I do?

By the way, thanks for this cool plugin!

**Comment by AVGVSTVS96** [comment]
you do not have access to the API. You need to sign up on the waitlist for GPT-4 API access.

**Comment by wuqui** [comment]
I see, that makes sense. Thanks for your prompt reply!
