### ISSUE TITLE
Cannot read properties of undefined (reading 'toLowerCase')

### ISSUE THREAD

**Issue by taariy** [debanjandhar12/logseq-chatgpt-plugin#22]
I am receiving the following error message: "Cannot read properties of undefined (reading 'toLowerCase')". This error message is causing the plugin to become unusable.

The error first appears as "The Ask ChatGPT button failed to mount. You can still use the Ask ChatGPT command/shortcut to interact with the page." After this, when I try to use the keyboard shortcut, I receive the error "Cannot read...", and the plugin stops working.

**Comment by RMTZen** [comment]
I have also been having this issue since I believe the release of 1.3.0, can we get an update on this please as it has stopped the plugin from being usable in it's present state

**Comment by debanjandhar12** [comment]
Can one of you share your OS version and logseq version please?

**Comment by RMTZen** [comment]
![image](https://github.com/debanjandhar12/logseq-chatgpt-plugin/assets/127308491/3cb3db00-e888-48c2-9a31-8106878e3a36)

![image](https://github.com/debanjandhar12/logseq-chatgpt-plugin/assets/127308491/520bfeae-b3b2-4015-b4be-22150f83b729)

But I've just seen there is an update for LogSeq which I have now ran, didn't realise I had fallen so far behind and it had got to 0.9.6 already, now the plugin is working again, was this was user error for me and I am sorry to have bothered you. 

@taariy, might be worth you double checking if your LogSeq needs updating as well.

**Comment by cnrpman** [comment]
It happens at this line
<img width="667" alt="image" src="https://github.com/debanjandhar12/logseq-chatgpt-plugin/assets/9862022/6ceb2b22-b781-41da-9051-1124c79c522d">

**Comment by cnrpman** [comment]
A solution is adding `:preferred-workflow :now` to your `config.edn` in Logseq

It happens when a graph is setup from a very old version of Logseq
From the plugin side, a solution is adding a `hasProperty` check
From Logseq side, it requires a better default key overriding for configs feed to plugins API 👀

**Comment by debanjandhar12** [comment]
> @taariy @RMTZen A solution is adding `:preferred-workflow :now` to your `config.edn` of the graph with this issue in Logseq.
> 
> It happens when a graph is setup from a very old version of Logseq (yes, it's a graph specific issue) From the plugin side, a solution is adding a `hasProperty` check From Logseq side, it requires a better default key overriding for configs feed to plugins API 👀

Thank you for the help. I have added an check for it in plugin too.
