### ISSUE TITLE
many tokens in completion

### ISSUE THREAD

**Issue by yangguang760** [debanjandhar12/logseq-chatgpt-plugin#27]
why there are so many tokens in completion?

![image](https://github.com/debanjandhar12/logseq-chatgpt-plugin/assets/748502/3dcdccf4-d57f-46b8-91b0-9e93f65a987e)

**Comment by debanjandhar12** [comment]
What is the current value set for Max Tokens in the plugin settings? Also, what model are you using?

![image](https://github.com/debanjandhar12/logseq-chatgpt-plugin/assets/49021233/9cd55e59-f302-46aa-9974-b8e44418c392)

---

The plugin works by deducting the current message length and setting the reminder as max length that the model is allowed to return. [This means that the model does not use max length even if it is allowed to do so. Chatgpt however disallows specifying max length value over their model's limit.]

**Comment by yangguang760** [comment]
![image](https://github.com/debanjandhar12/logseq-chatgpt-plugin/assets/748502/d2ea31f7-fd39-4640-bc59-f7bf820d7018)
![image](https://github.com/debanjandhar12/logseq-chatgpt-plugin/assets/748502/49d25795-ad77-47c0-b8ed-595043606f2a)

**Comment by debanjandhar12** [comment]
Setting the ChatGPT Max tokens to 4000 should fix the issue.

**Comment by yangguang760** [comment]
@debanjandhar12 Thanks a lot!
