### ISSUE TITLE
Question about token limit implementation

### ISSUE THREAD

**Issue by sumergoconicio** [debanjandhar12/logseq-chatgpt-plugin#29]
### Discussed in https://github.com/debanjandhar12/logseq-chatgpt-plugin/discussions/28

<div type='discussions-op-text'>

<sup>Originally posted by **sumergoconicio** July  6, 2023</sup>
First off, I LOVE this plugin. Thank you for making it and sharing it for free. It has changed my workflows and it is a tool I rely on daily nowadays.

I have a question, basically an error that arises after a long conversation. By default, ChatGPT stops responding, either mid-sentence or refuses to process the tokens with an error that token limits have been exceeded. My understanding is that the LLM basically looks at the last 8000 tokens in the conversation, right? 

So is there a hard limit to the length of a conversation e.g. max 20 back-and-forth chats to a limit of 8000 tokens OR is there effectively no limit since a rolling window of the last 8000 tokens are used EVEN IF the overall conversation has gone beyond that token limit?

So I want to understand why I get this error: 
<img width="404" alt="20230706-09 16 14AM -Logseq 004059@2x" src="https://github.com/debanjandhar12/logseq-chatgpt-plugin/assets/15786155/7671be0c-971e-418c-b03a-521422c6914b">

and if it can be counteracted with any settings on my side or code updates on your side?</div>

**Comment by debanjandhar12** [comment]
There is actually a rolling window but it is broken atm due a bug caused when updating langchain dependency.

I will fix that and do a release on the weekend.

**Comment by debanjandhar12** [comment]
I believe the error is now fixed (v2.0.3). If the error reoccurs, please re-open the issue.

**Comment by sumergoconicio** [comment]
Thanks Deban!

*Naveen Srivatsav*
Anticipatory Design & Emerging Technologies
https://www.glyphsandgraphs.com
https://www.facebook.com/sum.ergo.conicio
https://www.linkedin.com/in/naveensrivatsav/

**Comment by sumergoconicio** [comment]
Hi Deban

I believe there is still an error in the context window implementation. In the last few chats, when the context limit is exceeded, the error message does not pop up BUT the topic of the responses becomes incoherent with the bot responses diverging wildly from the actual topic under discussion in that chat. 

It was a pretty weird error actually, because it was answering as if asked some prompt in one of my earlier chats, as if it reverted to some cache to continue the conversation.
